data_table: dataset_table.csv
temp_dir: /scratch/users/dcotter1/metaSPLASH_workflows

# set paths to python venvs
envs:
  default_python: /oak/stanford/groups/horence/dcotter1/envs/biopython/bin/activate
  esm_env: /oak/stanford/groups/horence/dcotter1/envs/esm_venv/bin/activate

# define all scripts
scripts:
  anchor_select_script: 
    filter1: src/anchor_selection/select_anchors_filter1.R # arrange by nonzero samples then head
    filter2: src/anchor_selection/select_anchors_filter2.R # arrange by effect size then head
    filter3: src/anchor_selection/select_anchors_filter3.R # arrange by effect size * nonzero samples then head (see README for details)
  cluster_script: 
    shiftDist-keepTopES: 'python src/clustering/deduplication_clustering.py'
    shiftDist-keepMostAbundant: 'python src/clustering/deduplication_clustering.py'
    shiftDist-levFilter: 'python src/clustering/deduplication_clustering.py'
    mmseqs-levFilter: 'Rscript --vanilla src/clustering/cluster_with_mmseq.R'
  reorder_script:
    shiftDist-keepTopES: src/clustering/keep_topES_anchor_per_cluster.R
    shiftDist-keepMostAbundant: src/clustering/keep_mostAbundant_anchor_per_cluster.R
    shiftDist-levFilter: src/clustering/filter_clusters_by_distance.R
    mmseqs-levFilter: src/clustering/filter_clusters_by_distance.R
  match_kmers_to_clusters: src/process_seqs/id_kmers_per_cluster.R
  prepare_sequences: src/process_seqs/process_splash_data_for_embedding_align_clusters.R
  decompose_kmers: src/process_seqs/kmer_decomposition.py
  translate_script: src/process_seqs/translate_fasta.py
  extract_embeddings: src/esm_utils/extract_embeddings_from_torch_objects.py
  format_embeddings_variance: src/glmnet/grab_top_embeddings_by_variance.R
  format_sequences_ohe: src/process_seqs/one_hot_encode_anchor_clusters.R
  glmnet_script: src/glmnet/embeddings_glmnet.R