#!/usr/bin/env python3
"""
Permutation p-values for Flash classification accuracies.

The script expects a Flash output directory containing exactly one
*_confusion_matrices.pdf, then reads the matching sidecar table generated by
run_adelie.py/run_adelie_genomes.py. If no sidecar log is present, it falls
back to the matching *_nonzero_coefficients.tsv confusion_matrix column.
"""

import argparse
import csv
import glob
import math
import random
import sys
from collections import defaultdict
from fractions import Fraction
from pathlib import Path


LOG_COLUMNS = {
    "row_type",
    "metadata_category",
    "matrix",
    "true_label",
    "predicted_label",
    "n_samples",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute permutation-test p-values for Flash classification accuracy."
    )
    parser.add_argument(
        "--input_dir",
        "--input-dir",
        required=True,
        help="Directory containing one Flash *_confusion_matrices.pdf.",
    )
    parser.add_argument(
        "--metadata_category",
        "--metadata-category",
        "--metadata-categories",
        action="append",
        required=True,
        help=(
            "Metadata category to test. May be supplied multiple times or as a "
            "comma-separated list."
        ),
    )
    parser.add_argument(
        "--matrix",
        choices=("test", "train", "both"),
        default="test",
        help="Which confusion matrix to test. Default: test.",
    )
    parser.add_argument(
        "--permutations",
        type=int,
        default=10000,
        help="Number of Monte Carlo permutations. Default: 10000.",
    )
    parser.add_argument(
        "--method",
        choices=("auto", "exact", "monte_carlo"),
        default="auto",
        help=(
            "P-value method. auto uses exact enumeration when feasible and "
            "otherwise falls back to Monte Carlo. Default: auto."
        ),
    )
    parser.add_argument(
        "--max_exact_states",
        "--max-exact-states",
        type=int,
        default=2000000,
        help="Maximum dynamic-programming states for --method auto/exact. Default: 2000000.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for permutations. Default: 42.",
    )
    parser.add_argument(
        "--pdf",
        default="",
        help="Optional explicit confusion-matrix PDF path.",
    )
    parser.add_argument(
        "--sidecar",
        default="",
        help="Optional explicit confusion log or nonzero-coefficients TSV/CSV.",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Optional output TSV. Results are always printed to stdout.",
    )
    return parser.parse_args()


def split_requested_categories(values):
    categories = []
    for value in values:
        categories.extend(part.strip() for part in value.split(",") if part.strip())
    return list(dict.fromkeys(categories))


def sniff_delimiter(path):
    if Path(path).suffix.lower() == ".csv":
        return ","
    with open(path, "r", newline="") as handle:
        sample = handle.read(4096)
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters="\t,")
        return dialect.delimiter
    except csv.Error:
        return "\t"


def read_table(path):
    delimiter = sniff_delimiter(path)
    with open(path, "r", newline="") as handle:
        reader = csv.DictReader(handle, delimiter=delimiter)
        return list(reader), list(reader.fieldnames or [])


def has_glob_magic(value):
    return any(char in str(value) for char in "*?[")


def resolve_one_path(value, label, base_dir=None):
    path_text = str(value)
    candidate_texts = [path_text]
    path = Path(path_text)
    if base_dir and not path.is_absolute():
        candidate_texts.insert(0, str(Path(base_dir) / path_text))

    matches = []
    for candidate in candidate_texts:
        if has_glob_magic(candidate):
            matches.extend(glob.glob(candidate, recursive=True))
        elif Path(candidate).exists():
            matches.append(candidate)

    unique_matches = sorted(dict.fromkeys(str(Path(match)) for match in matches))
    if not unique_matches:
        base_message = f" relative to {base_dir}" if base_dir else ""
        raise FileNotFoundError(f"No {label} matched {value!r}{base_message}.")
    if len(unique_matches) > 1:
        joined = "\n  ".join(unique_matches[:20])
        raise ValueError(
            f"{label} pattern matched more than one file. Please narrow it.\n"
            f"  {joined}"
        )
    return Path(unique_matches[0])


def find_confusion_pdf(input_dir, explicit_pdf=""):
    if explicit_pdf:
        return resolve_one_path(explicit_pdf, "PDF", base_dir=input_dir)

    pdfs = sorted(Path(input_dir).rglob("*_confusion_matrices.pdf"))
    if not pdfs:
        raise FileNotFoundError(
            f"No *_confusion_matrices.pdf found below {input_dir}."
        )
    if len(pdfs) > 1:
        joined = "\n  ".join(str(path) for path in pdfs[:20])
        raise ValueError(
            "Found more than one confusion-matrix PDF. Re-run with --pdf.\n"
            f"  {joined}"
        )
    return pdfs[0]


def sidecar_candidates(pdf):
    candidates = [
        pdf.with_suffix(".tsv"),
        pdf.with_suffix(".csv"),
    ]
    stem = pdf.stem
    if stem.endswith("_confusion_matrices"):
        prefix = stem[: -len("_confusion_matrices")]
        candidates.extend(
            [
                pdf.with_name(prefix + "_nonzero_coefficients.tsv"),
                pdf.with_name(prefix + "_nonzero_coefficients.csv"),
                pdf.with_name(prefix + "_nonzero_coefficients_annotated.tsv"),
                pdf.with_name(prefix + "_nonzero_coefficients_annotated.csv"),
            ]
        )
    return candidates


def find_sidecar(pdf, explicit_sidecar=""):
    if explicit_sidecar:
        return resolve_one_path(explicit_sidecar, "sidecar", base_dir=pdf.parent)

    for candidate in sidecar_candidates(pdf):
        if candidate.exists():
            return candidate
    tried = "\n  ".join(str(path) for path in sidecar_candidates(pdf))
    raise FileNotFoundError(
        "Could not find a sidecar confusion log or coefficient TSV for:\n"
        f"  {pdf}\nTried:\n  {tried}"
    )


def accuracy(true_labels, predicted_labels):
    if len(true_labels) != len(predicted_labels):
        raise ValueError("true/predicted label vectors have different lengths")
    if not true_labels:
        raise ValueError("empty confusion matrix")
    correct = sum(t == p for t, p in zip(true_labels, predicted_labels))
    return correct / len(true_labels)


def pvalue_from_vectors(true_labels, predicted_labels, permutations, rng):
    observed = accuracy(true_labels, predicted_labels)
    permuted_true = list(true_labels)
    ge_observed = 0
    for _ in range(permutations):
        rng.shuffle(permuted_true)
        if accuracy(permuted_true, predicted_labels) >= observed:
            ge_observed += 1
    return observed, ge_observed, (1 + ge_observed) / (permutations + 1)


def label_counts(labels, ordered_labels):
    return [sum(label == target for label in labels) for target in ordered_labels]


def generate_allocations(total, caps):
    allocation = [0] * len(caps)

    def rec(index, remaining):
        if index == len(caps) - 1:
            if 0 <= remaining <= caps[index]:
                allocation[index] = remaining
                yield tuple(allocation)
            return
        upper = min(caps[index], remaining)
        for value in range(upper + 1):
            allocation[index] = value
            yield from rec(index + 1, remaining - value)

    yield from rec(0, total)


def exact_pvalue_from_vectors(true_labels, predicted_labels, max_states):
    observed_correct = sum(t == p for t, p in zip(true_labels, predicted_labels))
    labels = sorted(set(true_labels) | set(predicted_labels))
    true_counts = label_counts(true_labels, labels)
    predicted_counts = label_counts(predicted_labels, labels)

    states = {(tuple(predicted_counts), 0): 1}
    states_seen = 1
    for true_index, row_total in enumerate(true_counts):
        next_states = defaultdict(int)
        for (remaining_columns, correct_so_far), ways_so_far in states.items():
            for allocation in generate_allocations(row_total, remaining_columns):
                ways = ways_so_far
                for remaining, chosen in zip(remaining_columns, allocation):
                    ways *= math.comb(remaining, chosen)
                next_remaining = tuple(
                    remaining - chosen
                    for remaining, chosen in zip(remaining_columns, allocation)
                )
                next_correct = correct_so_far + allocation[true_index]
                next_states[(next_remaining, next_correct)] += ways
        states = dict(next_states)
        states_seen += len(states)
        if states_seen > max_states:
            raise RuntimeError(
                f"Exact p-value exceeded --max_exact_states={max_states}."
            )

    total_ways = 0
    tail_ways = 0
    zero_remaining = tuple([0] * len(labels))
    for (remaining_columns, correct), ways in states.items():
        if remaining_columns != zero_remaining:
            continue
        total_ways += ways
        if correct >= observed_correct:
            tail_ways += ways
    if total_ways == 0:
        raise ValueError("Exact p-value calculation found no valid permutations.")
    p_value = Fraction(tail_ways, total_ways)
    return observed_correct / len(true_labels), observed_correct, tail_ways, total_ways, p_value


def vectors_from_log(rows, metadata_category, matrix):
    selected = [
        row
        for row in rows
        if row.get("metadata_category") == metadata_category
        and row.get("matrix") == matrix
    ]
    sample_rows = [
        row
        for row in selected
        if row.get("row_type") == "sample"
        and row.get("true_label", "") != ""
        and row.get("predicted_label", "") != ""
    ]
    if sample_rows:
        return (
            [row["true_label"] for row in sample_rows],
            [row["predicted_label"] for row in sample_rows],
            "sample_rows",
        )

    entry_rows = [
        row
        for row in selected
        if row.get("row_type") == "entry"
        and row.get("true_label", "") != ""
        and row.get("predicted_label", "") != ""
    ]
    true_labels = []
    predicted_labels = []
    for row in entry_rows:
        n = int(float(row.get("n_samples") or 0))
        true_labels.extend([row["true_label"]] * n)
        predicted_labels.extend([row["predicted_label"]] * n)
    if true_labels:
        return true_labels, predicted_labels, "entry_counts"
    return None, None, ""


def parse_confusion_matrix(value):
    value = (value or "").strip()
    if not value or value == "NA":
        return None
    if not (value.startswith("{") and value.endswith("}")):
        raise ValueError(f"Unsupported confusion_matrix format: {value}")
    rows = []
    for row_text in value[1:-1].split(";"):
        rows.append([int(float(cell)) for cell in row_text.split(",") if cell != ""])
    if not rows or any(len(row) != len(rows[0]) for row in rows):
        raise ValueError(f"Invalid confusion_matrix value: {value}")
    return rows


def vectors_from_matrix(counts, class_labels=None):
    n = len(counts)
    if class_labels is None or len(class_labels) != n:
        class_labels = [str(i) for i in range(n)]
    true_labels = []
    predicted_labels = []
    for i, row in enumerate(counts):
        for j, count in enumerate(row):
            true_labels.extend([class_labels[i]] * count)
            predicted_labels.extend([class_labels[j]] * count)
    return true_labels, predicted_labels


def parse_classes(value):
    value = (value or "").strip()
    if not value.startswith("[") or not value.endswith("]"):
        return None
    labels = [part.strip() for part in value[1:-1].split(",")]
    labels = [label for label in labels if label]
    return labels or None


def vectors_from_coefficients(rows, metadata_category):
    matches = [row for row in rows if row.get("metadata_category") == metadata_category]
    for row in matches:
        counts = parse_confusion_matrix(row.get("confusion_matrix", ""))
        if counts is None:
            continue
        return (*vectors_from_matrix(counts, parse_classes(row.get("classes", ""))), "confusion_matrix")
    return None, None, ""


def table_kind(fieldnames):
    fields = set(fieldnames)
    if LOG_COLUMNS <= fields:
        return "confusion_log"
    if {"metadata_category", "confusion_matrix"} <= fields:
        return "coefficients"
    raise ValueError(
        "Sidecar must be a Flash confusion log or a coefficient table with "
        "metadata_category and confusion_matrix columns."
    )


def result_rows(
    rows,
    fieldnames,
    categories,
    matrices,
    permutations,
    seed,
    method,
    max_exact_states,
):
    kind = table_kind(fieldnames)
    output = []
    for category in categories:
        for matrix in matrices:
            if kind == "confusion_log":
                true_labels, predicted_labels, source = vectors_from_log(
                    rows, category, matrix
                )
            else:
                if matrix != "test":
                    continue
                true_labels, predicted_labels, source = vectors_from_coefficients(
                    rows, category
                )
            if true_labels is None:
                raise ValueError(
                    f"No classification confusion data found for "
                    f"metadata_category={category!r}, matrix={matrix!r}."
                )

            pvalue_method = method
            exact_tail = ""
            exact_total = ""
            ge_observed = ""
            minimum_possible = ""
            if method in {"auto", "exact"}:
                try:
                    (
                        observed,
                        observed_correct,
                        exact_tail,
                        exact_total,
                        exact_p_value,
                    ) = exact_pvalue_from_vectors(
                        true_labels, predicted_labels, max_exact_states
                    )
                    p_value = float(exact_p_value)
                    pvalue_method = "exact"
                except RuntimeError:
                    if method == "exact":
                        raise
                    pvalue_method = "monte_carlo"

            if pvalue_method == "monte_carlo":
                rng = random.Random(f"{seed}:{category}:{matrix}")
                observed, ge_observed, p_value = pvalue_from_vectors(
                    true_labels, predicted_labels, permutations, rng
                )
                minimum_possible = f"{1 / (permutations + 1):.10g}"

            output.append(
                {
                    "metadata_category": category,
                    "matrix": matrix,
                    "n_samples": len(true_labels),
                    "observed_accuracy": f"{observed:.10g}",
                    "method": pvalue_method,
                    "permutations": permutations,
                    "permuted_ge_observed": ge_observed,
                    "p_value": f"{p_value:.10g}",
                    "minimum_possible_p_value": minimum_possible,
                    "exact_tail_permutations": exact_tail,
                    "exact_total_permutations": exact_total,
                    "source": source,
                }
            )
    return output


def write_rows(rows, output_path=""):
    fieldnames = [
        "metadata_category",
        "matrix",
        "n_samples",
        "observed_accuracy",
        "method",
        "permutations",
        "permuted_ge_observed",
        "p_value",
        "minimum_possible_p_value",
        "exact_tail_permutations",
        "exact_total_permutations",
        "source",
    ]
    writer = csv.DictWriter(sys.stdout, fieldnames=fieldnames, delimiter="\t")
    writer.writeheader()
    writer.writerows(rows)

    if output_path:
        with open(output_path, "w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
            writer.writeheader()
            writer.writerows(rows)


def main():
    args = parse_args()
    if args.permutations < 1:
        raise ValueError("--permutations must be at least 1")

    categories = split_requested_categories(args.metadata_category)
    matrices = ["test", "train"] if args.matrix == "both" else [args.matrix]
    pdf = find_confusion_pdf(args.input_dir, args.pdf)
    sidecar = find_sidecar(pdf, args.sidecar)
    rows, fieldnames = read_table(sidecar)
    results = result_rows(
        rows,
        fieldnames,
        categories,
        matrices,
        args.permutations,
        args.seed,
        args.method,
        args.max_exact_states,
    )
    write_rows(results, args.output)


if __name__ == "__main__":
    main()
