#!/usr/bin/env python3
"""
Permutation p-values for Flash classification accuracies.

The script expects a Flash output directory containing exactly one
*_confusion_matrices.pdf, then reads the matching sidecar table generated by
run_adelie.py/run_adelie_genomes.py. If no sidecar log is present, it falls
back to the matching *_nonzero_coefficients.tsv confusion_matrix column.
"""

import argparse
import csv
import random
import re
import sys
from pathlib import Path


LOG_COLUMNS = {
    "row_type",
    "metadata_category",
    "matrix",
    "true_label",
    "predicted_label",
    "n_samples",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute permutation-test p-values for Flash classification accuracy."
    )
    parser.add_argument(
        "--input_dir",
        "--input-dir",
        required=True,
        help="Directory containing one Flash *_confusion_matrices.pdf.",
    )
    parser.add_argument(
        "--metadata_category",
        "--metadata-category",
        "--metadata-categories",
        action="append",
        required=True,
        help=(
            "Metadata category to test. May be supplied multiple times or as a "
            "comma-separated list."
        ),
    )
    parser.add_argument(
        "--matrix",
        choices=("test", "train", "both"),
        default="test",
        help="Which confusion matrix to test. Default: test.",
    )
    parser.add_argument(
        "--permutations",
        type=int,
        default=10000,
        help="Number of permutations. Default: 10000.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for permutations. Default: 42.",
    )
    parser.add_argument(
        "--pdf",
        default="",
        help="Optional explicit confusion-matrix PDF path.",
    )
    parser.add_argument(
        "--sidecar",
        default="",
        help="Optional explicit confusion log or nonzero-coefficients TSV/CSV.",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Optional output TSV. Results are always printed to stdout.",
    )
    return parser.parse_args()


def split_requested_categories(values):
    categories = []
    for value in values:
        categories.extend(part.strip() for part in value.split(",") if part.strip())
    return list(dict.fromkeys(categories))


def sniff_delimiter(path):
    if Path(path).suffix.lower() == ".csv":
        return ","
    with open(path, "r", newline="") as handle:
        sample = handle.read(4096)
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters="\t,")
        return dialect.delimiter
    except csv.Error:
        return "\t"


def read_table(path):
    delimiter = sniff_delimiter(path)
    with open(path, "r", newline="") as handle:
        reader = csv.DictReader(handle, delimiter=delimiter)
        return list(reader), list(reader.fieldnames or [])


def find_confusion_pdf(input_dir, explicit_pdf=""):
    if explicit_pdf:
        pdf = Path(explicit_pdf)
        if not pdf.exists():
            raise FileNotFoundError(f"Explicit PDF does not exist: {pdf}")
        return pdf

    pdfs = sorted(Path(input_dir).rglob("*_confusion_matrices.pdf"))
    if not pdfs:
        raise FileNotFoundError(
            f"No *_confusion_matrices.pdf found below {input_dir}."
        )
    if len(pdfs) > 1:
        joined = "\n  ".join(str(path) for path in pdfs[:20])
        raise ValueError(
            "Found more than one confusion-matrix PDF. Re-run with --pdf.\n"
            f"  {joined}"
        )
    return pdfs[0]


def sidecar_candidates(pdf):
    candidates = [
        pdf.with_suffix(".tsv"),
        pdf.with_suffix(".csv"),
    ]
    stem = pdf.stem
    if stem.endswith("_confusion_matrices"):
        prefix = stem[: -len("_confusion_matrices")]
        candidates.extend(
            [
                pdf.with_name(prefix + "_nonzero_coefficients.tsv"),
                pdf.with_name(prefix + "_nonzero_coefficients.csv"),
                pdf.with_name(prefix + "_nonzero_coefficients_annotated.tsv"),
                pdf.with_name(prefix + "_nonzero_coefficients_annotated.csv"),
            ]
        )
    return candidates


def find_sidecar(pdf, explicit_sidecar=""):
    if explicit_sidecar:
        sidecar = Path(explicit_sidecar)
        if not sidecar.exists():
            raise FileNotFoundError(f"Explicit sidecar does not exist: {sidecar}")
        return sidecar

    for candidate in sidecar_candidates(pdf):
        if candidate.exists():
            return candidate
    tried = "\n  ".join(str(path) for path in sidecar_candidates(pdf))
    raise FileNotFoundError(
        "Could not find a sidecar confusion log or coefficient TSV for:\n"
        f"  {pdf}\nTried:\n  {tried}"
    )


def accuracy(true_labels, predicted_labels):
    if len(true_labels) != len(predicted_labels):
        raise ValueError("true/predicted label vectors have different lengths")
    if not true_labels:
        raise ValueError("empty confusion matrix")
    correct = sum(t == p for t, p in zip(true_labels, predicted_labels))
    return correct / len(true_labels)


def pvalue_from_vectors(true_labels, predicted_labels, permutations, rng):
    observed = accuracy(true_labels, predicted_labels)
    permuted_true = list(true_labels)
    ge_observed = 0
    for _ in range(permutations):
        rng.shuffle(permuted_true)
        if accuracy(permuted_true, predicted_labels) >= observed:
            ge_observed += 1
    return observed, ge_observed, (1 + ge_observed) / (permutations + 1)


def vectors_from_log(rows, metadata_category, matrix):
    selected = [
        row
        for row in rows
        if row.get("metadata_category") == metadata_category
        and row.get("matrix") == matrix
    ]
    sample_rows = [
        row
        for row in selected
        if row.get("row_type") == "sample"
        and row.get("true_label", "") != ""
        and row.get("predicted_label", "") != ""
    ]
    if sample_rows:
        return (
            [row["true_label"] for row in sample_rows],
            [row["predicted_label"] for row in sample_rows],
            "sample_rows",
        )

    entry_rows = [
        row
        for row in selected
        if row.get("row_type") == "entry"
        and row.get("true_label", "") != ""
        and row.get("predicted_label", "") != ""
    ]
    true_labels = []
    predicted_labels = []
    for row in entry_rows:
        n = int(float(row.get("n_samples") or 0))
        true_labels.extend([row["true_label"]] * n)
        predicted_labels.extend([row["predicted_label"]] * n)
    if true_labels:
        return true_labels, predicted_labels, "entry_counts"
    return None, None, ""


def parse_confusion_matrix(value):
    value = (value or "").strip()
    if not value or value == "NA":
        return None
    if not (value.startswith("{") and value.endswith("}")):
        raise ValueError(f"Unsupported confusion_matrix format: {value}")
    rows = []
    for row_text in value[1:-1].split(";"):
        rows.append([int(float(cell)) for cell in row_text.split(",") if cell != ""])
    if not rows or any(len(row) != len(rows[0]) for row in rows):
        raise ValueError(f"Invalid confusion_matrix value: {value}")
    return rows


def vectors_from_matrix(counts, class_labels=None):
    n = len(counts)
    if class_labels is None or len(class_labels) != n:
        class_labels = [str(i) for i in range(n)]
    true_labels = []
    predicted_labels = []
    for i, row in enumerate(counts):
        for j, count in enumerate(row):
            true_labels.extend([class_labels[i]] * count)
            predicted_labels.extend([class_labels[j]] * count)
    return true_labels, predicted_labels


def parse_classes(value):
    value = (value or "").strip()
    if not value.startswith("[") or not value.endswith("]"):
        return None
    labels = [part.strip() for part in value[1:-1].split(",")]
    labels = [label for label in labels if label]
    return labels or None


def vectors_from_coefficients(rows, metadata_category):
    matches = [row for row in rows if row.get("metadata_category") == metadata_category]
    for row in matches:
        counts = parse_confusion_matrix(row.get("confusion_matrix", ""))
        if counts is None:
            continue
        return (*vectors_from_matrix(counts, parse_classes(row.get("classes", ""))), "confusion_matrix")
    return None, None, ""


def table_kind(fieldnames):
    fields = set(fieldnames)
    if LOG_COLUMNS <= fields:
        return "confusion_log"
    if {"metadata_category", "confusion_matrix"} <= fields:
        return "coefficients"
    raise ValueError(
        "Sidecar must be a Flash confusion log or a coefficient table with "
        "metadata_category and confusion_matrix columns."
    )


def result_rows(rows, fieldnames, categories, matrices, permutations, seed):
    kind = table_kind(fieldnames)
    output = []
    for category in categories:
        for matrix in matrices:
            if kind == "confusion_log":
                true_labels, predicted_labels, source = vectors_from_log(
                    rows, category, matrix
                )
            else:
                if matrix != "test":
                    continue
                true_labels, predicted_labels, source = vectors_from_coefficients(
                    rows, category
                )
            if true_labels is None:
                raise ValueError(
                    f"No classification confusion data found for "
                    f"metadata_category={category!r}, matrix={matrix!r}."
                )

            rng = random.Random(f"{seed}:{category}:{matrix}")
            observed, ge_observed, p_value = pvalue_from_vectors(
                true_labels, predicted_labels, permutations, rng
            )
            output.append(
                {
                    "metadata_category": category,
                    "matrix": matrix,
                    "n_samples": len(true_labels),
                    "observed_accuracy": f"{observed:.10g}",
                    "permutations": permutations,
                    "permuted_ge_observed": ge_observed,
                    "p_value": f"{p_value:.10g}",
                    "source": source,
                }
            )
    return output


def write_rows(rows, output_path=""):
    fieldnames = [
        "metadata_category",
        "matrix",
        "n_samples",
        "observed_accuracy",
        "permutations",
        "permuted_ge_observed",
        "p_value",
        "source",
    ]
    writer = csv.DictWriter(sys.stdout, fieldnames=fieldnames, delimiter="\t")
    writer.writeheader()
    writer.writerows(rows)

    if output_path:
        with open(output_path, "w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
            writer.writeheader()
            writer.writerows(rows)


def main():
    args = parse_args()
    if args.permutations < 1:
        raise ValueError("--permutations must be at least 1")

    categories = split_requested_categories(args.metadata_category)
    matrices = ["test", "train"] if args.matrix == "both" else [args.matrix]
    pdf = find_confusion_pdf(args.input_dir, args.pdf)
    sidecar = find_sidecar(pdf, args.sidecar)
    rows, fieldnames = read_table(sidecar)
    results = result_rows(
        rows,
        fieldnames,
        categories,
        matrices,
        args.permutations,
        args.seed,
    )
    write_rows(results, args.output)


if __name__ == "__main__":
    main()
