executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/`date +"%d-%m-%y"`/{rule};
  sbatch
    --parsable
    --time={resources.time}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%d-%m-%y"`/{rule}/{rule}-{wildcards}-%j.out
    {resources.slurm_extra}
default-resources:
  - time="2:00:00"
  - partition="horence,owners,normal"
  - mem_mb=4000
  - slurm_extra=""
  - msa=1
jobs: 2000
local-cores: 1
max-jobs-per-second: 500
max-status-checks-per-second: 15
restart-times: 2
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
cluster-generic-cancel-cmd: scancel
scheduler: greedy
set-resources: # set specific resources for each rule
    choose_anchors:
        threads: 4
        resources:
            mem_mb: 128000
            time: "4:00:00"
    cluster_anchors:
        threads: 4
        resources:
            mem_mb: lambda wildcards, attempt: 640000 + ((attempt - 1) * 128000) if (wildcards.cluster_type == "masked-aa-clustered" or wildcards.cluster_type == "masked-nucleotide-clustered") else 64000 + ((attempt - 1) * 128000)
            time: lambda wildcards, attempt: "12:00:00" if (wildcards.cluster_type == "masked-aa-clustered" or wildcards.cluster_type == "masked-nucleotide-clustered") else "3:00:00"
    reorder_clusters:
        threads: 32
        resources:
            mem_mb: lambda _, attempt: 64000 + ((attempt - 1) * 64000)
            time: "5:00:00"
    select_N_clusters:
        threads: 1
        resources: {}
    prepare_sequences:
        threads: 16
        resources:
            mem_mb: 128000
    decompose_kmers:
        threads: 1
        resources:
            mem_mb: lambda _, attempt: 32000 + ((attempt - 1) * 32000)
            time: "3:00:00"
    match_kmers_to_clusters:
        threads: 1
        resources:
            mem_mb: lambda _, attempt: 16000 + ((attempt - 1) * 16000)
    embed_kmers_hyena:
        threads: 8
        resources:
            mem_mb: 32000
            time: "6:00:00"
            partition: "horence,gpu,owners"
            slurm_extra: "-G 1 -C 'GPU_GEN:HPR|GPU_GEN:AMP|GPU_GEN:TUR'"
    prepare_data_for_prediction_top_variance:
        threads: 32
        resources:
            mem_mb: lambda _, attempt: 256000 + ((attempt - 1) * 256000)
            time: "6:00:00"
    run_adelie:
        threads: 32
        resources:
            mem_mb: lambda _, attempt: 512000 + ((attempt - 1) * 128000)
            time: "24:00:00"
    prepare_data_for_prediction_ohe:
        threads: 4
        resources:
            mem_mb: lambda _, attempt: 96000 + ((attempt - 1) * 64000)
            time: "3:00:00"
    run_adelie_ohe:
        threads: 16
        resources:
            mem_mb: lambda _, attempt: 128000 + ((attempt - 1) * 64000)
            time: "18:00:00"
    process_genome_to_sample_sequences:
        threads: 16
        resources:
            mem_mb: 128000
    decompose_kmers_genomes:
        threads: 1
        resources:
            mem_mb: lambda _, attempt: 16000 + ((attempt - 1) * 16000)
            time: "3:00:00"
    embed_kmers_hyena_genomes:
        threads: 8
        resources:
            mem_mb: 32000
            time: "3:00:00"
            partition: "horence,gpu,owners"
            slurm_extra: "-G 1 -C 'GPU_GEN:HPR|GPU_GEN:AMP|GPU_GEN:TUR'"
    prepare_data_for_prediction_genomes:
        threads: 32
        resources:
            mem_mb: lambda _, attempt: 256000 + ((attempt - 1) * 256000)
    run_adelie_genomes:
        threads: 64
        resources:
            mem_mb: lambda _, attempt: 512000 + ((attempt - 1) * 128000)
            time: "36:00:00"
    annotate_clusters:
        threads: 4
        resources:
            mem_mb: lambda _, attempt: 64000 + ((attempt - 1) * 32000)
    merge_annotations:
        threads: 1
        resources:
            mem_mb: lambda _, attempt: 64000 + ((attempt - 1) * 32000)
    run_blast_nonzero_features:
        threads: 16
        resources:
            mem_mb: 128000
            time: "9:00:00"
    run_blastp_nonzero_features:
        threads: 16
        resources:
            mem_mb: lambda _, attempt: 256000 + ((attempt - 1) * 128000)
            time: "12:00:00"
    merge_blast_results:
        threads: 1
        resources:
            mem_mb: 8000
    merge_blastp_results:
        threads: 1
        resources:
            mem_mb: 8000
    merge_annotations_OHE:
        threads: 1
        resources:
            mem_mb: 32000
    run_blast_nonzero_features_OHE:
        threads: 16
        resources:
            mem_mb: 128000
            time: "9:00:00"
    run_blastp_nonzero_features_OHE:
        threads: 16
        resources:
            mem_mb: lambda _, attempt: 256000 + ((attempt - 1) * 128000)
            time: "9:00:00"
    merge_blast_results_OHE:
        threads: 1
        resources:
            mem_mb: 8000
    merge_blastp_results_OHE:
        threads: 1
        resources:
            mem_mb: 8000
    merge_annotations_genomes:
        threads: 1
        resources:
            mem_mb: 32000
    plot_blast_features:
        threads: 1
        resources:
            mem_mb: 128000
            msa: 1
            time: "4:00:00"
    plot_blast_heatmaps:
        threads: 1
        resources:
            mem_mb: 128000
    plot_blast_features_OHE:
        threads: 1
        resources:
            mem_mb: 128000
            msa: 1
    plot_blast_heatmaps_OHE:
        threads: 1
        resources:
            mem_mb: 128000
    prepare_data_for_umap_top_variance:
        threads: 32
        resources:
            mem_mb: lambda _, attempt: 256000 + ((attempt - 1) * 256000)
            time: "6:00:00"
    plot_embeddings_umap:
        threads: 16
        resources:
            mem_mb: lambda _, attempt: 128000 + ((attempt - 1) * 128000)
            time: "2:00:00"